---
title: "5513 - Assignment 3"
format: 
  html:
    embed-resources: true
  pdf:
    toc: true
    embed-resources: true
knitr:
  opts_chunk:
    warning: false
    message: false
    eval: true
    echo: false
editor: visual
---

## 5. Discussion

**Number of hours students spends using social media per day:** Students might become so indulged in social media that they lose track of their time. This time allocation reduces the amount of time they have for other activities, which not only affects them in the short term, but in the long term. They can lose a large amount of time that they could have spent on personal development, family, friends and society.

**Reported number of arguments or disagreements student have with their family, friends and/or partners:** Social media addiction increases the likelihood of students having conflicts with others. There are two causes or mediating factors may explain this result:

1.  Maybe student's consumption of negative content on social media affects their mental health and behavior, including posts that call for toxic self-expression, support self-righteousness, etc.

2.  Excessive screen time can increase stress in young people (Martin P. Paulus et al., 2023). Because of the psychological instability caused by screen light, they may have harsh reactions, get angry easily, and often argue with others more.

**Student have had their academic result impacted by using social media:** Here are two potential explanations:

1.  Spending too much time on social media takes away from the time students could have spent on studying. A student who would have had 6 hours to do homework and review lessons spends that time on social media.

2.  The brain tends to prefer easy activities. Studying requires the brain to work hard, while surfing social media does not require students to think much. Over time, students may find it difficult and exhausting to think or analyze logically.
